services:
    phd_exceptional_validation.violations_list_formatter:
        class: PhPhD\ExceptionalValidation\Formatter\List\DefaultExceptionListViolationFormatter
        arguments:
            - '@phd_exceptional_validation.violation_formatter'
        lazy: true
        tags:
            - { name: 'proxy', interface: 'PhPhD\ExceptionalValidation\Formatter\List\ExceptionListViolationFormatter' }
