services:
    phd_exceptional_validation.match_condition_factory:
        class: PhPhD\ExceptionalValidation\Model\Condition\CaptureMatchConditionFactory
        arguments:
            - !tagged_locator { tag: 'exceptional_validation.match_condition_factory', index_by: 'id' }
