services:
    phd_exceptional_validation.rule_set_assembler.object:
        class: PhPhD\ExceptionalValidation\Rule\Object\Assembler\ObjectRuleSetAssembler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler.object.rules'

    phd_exceptional_validation.rule_set_assembler.object.rules:
        class: PhPhD\ExceptionalValidation\Rule\Object\Assembler\Rules\ObjectRulesAssembler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler.property'

    phd_exceptional_validation.rule_set_assembler.property:
        class: PhPhD\ExceptionalValidation\Rule\Object\Property\Assembler\PropertyRuleSetAssembler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler.property.rules'

    phd_exceptional_validation.rule_set_assembler.property.rules:
        class: PhPhD\ExceptionalValidation\Rule\Assembler\CompositeRuleSetAssembler
        arguments:
            -   - '@phd_exceptional_validation.rule_set_assembler.property.rules.captures'
                - '@phd_exceptional_validation.rule_set_assembler.property.rules.nested_valid_object'
                - '@phd_exceptional_validation.rule_set_assembler.property.rules.nested_valid_iterable'

    phd_exceptional_validation.rule_set_assembler.property.rules.captures:
        class: PhPhD\ExceptionalValidation\Rule\Object\Property\Capture\Assembler\PropertyCaptureRulesAssembler
        arguments: [ '@phd_exceptional_validation.match_condition_factory' ]

    phd_exceptional_validation.rule_set_assembler.property.rules.nested_valid_object:
        class: PhPhD\ExceptionalValidation\Rule\Object\Property\Assembler\Rules\PropertyNestedValidObjectRuleAssembler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler.object'
        lazy: true
        tags:
            - { name: 'proxy', interface: 'PhPhD\ExceptionalValidation\Rule\Assembler\CaptureRuleSetAssembler' }

    phd_exceptional_validation.rule_set_assembler.property.rules.nested_valid_iterable:
        class: PhPhD\ExceptionalValidation\Rule\Object\Property\Assembler\Rules\PropertyNestedValidIterableRulesAssembler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler.iterable_of_objects'
        lazy: true
        tags:
            - { name: 'proxy', interface: 'PhPhD\ExceptionalValidation\Rule\Assembler\CaptureRuleSetAssembler' }

    phd_exceptional_validation.rule_set_assembler.iterable_of_objects:
        class: PhPhD\ExceptionalValidation\Rule\Object\Assembler\IterableOfObjectsRuleSetAssembler
        arguments:
            - '@phd_exceptional_validation.rule_set_assembler.object'
